### ISSUE TITLE
Unhandled Exception - System.TimeoutException

### ISSUE THREAD

**Issue by robocop99** [TheRealDF/ADFGX_Cloud_Solver#10]
in V5 i get this exception that occurs after i leave it running for a bit:

An unhandled exception of type 'System.TimeoutException' occurred in mscorlib.dll

Additional information: The request channel timed out while waiting for a reply after 00:00:59.7289337. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.

**Comment by Javano** [comment]
This is already handled in my #8 patch. Just waiting on DF to roll it out with V6. :)

However, we should still investigate if this can be mitigated server-side, because I also get this error at an unusually-common rate.

**Comment by robocop99** [comment]
Ok cool was just making sure you guys knew 👍  I'll keep an eye out for anything else. Helps having VS on my pc to debug errors if anything comes up :)

**Comment by TheRealDF** [comment]
@Javano @robocop99 Javano's fixes have now been rolled out, but we have also completely changed the backend from a wcf, to a simple post.

M$ has ALOT of shit to work out with WCF services before i will EVER use them again. Good 'ol HTTP POST has solved all http errors and is a shit load faster. WCF was maxing my server out

**Comment by TheRealDF** [comment]
Fixed in v6

**Comment by Javano** [comment]
That explains a lot... Lmfao.
![dialogues](https://cloud.githubusercontent.com/assets/6813253/19843185/84020404-9ee5-11e6-9e41-db6c78a86811.PNG)
