### ISSUE TITLE
Possible Fraudulent Results?

### ISSUE THREAD

**Issue by Javano** [TheRealDF/ADFGX_Cloud_Solver#12]
Unless these three guys repurposed some bitcoin-mining server farms, I feel like these results are impossibly-unlikely:

![results](https://cloud.githubusercontent.com/assets/6813253/19868306/16564a36-9f6d-11e6-869d-6e7ff8b75306.png)

Could you verify the legitimacy of these?

**Comment by TheRealDF** [comment]
Sadly a few people wont update their service. which means their score threshold is lower. Working on a way to filter these out.

**Comment by Javano** [comment]
It seems like you were able to handle this issue -- and if what you say about old builds becoming useless once the WCF service is axed is true, it seems like this shouldn't be an issue in the future (unless the scoring algorithm is changed again, which I assume will be better planned for next time).

Closing this ticket.
