### ISSUE TITLE
Unhandled exception occurred in mscorlib.dll

### ISSUE THREAD

**Issue by robocop99** [TheRealDF/ADFGX_Cloud_Solver#13]
Did a fresh download today and built the solution myself. After it was running for a while it went not responding with the following exception, presume the server is playing up?

An unhandled exception of type 'System.ServiceModel.ProtocolException' occurred in mscorlib.dll

Additional information: The content type text/html of the response message does not match the content type of the binding (text/xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly. The first 1024 bytes of the response were: '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>

<title>500 - Internal server error.</title>

<style type="text/css">

<!--

body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}

fieldset{padding:0 15px 10px 15px;} 

h1{font-size:2.4em;margin:0;color:#FFF;}

h2{font-size:1.7em;margin:0;color:#CC0000;} 

h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 

#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;

background-color:#555555;}

**Comment by Javano** [comment]
The source on this repo is not up to date. (v5 vs v6)

AFAIK, DF changed the connection protocol from WCF to HTTP POSTs in v6 -- and I know he mentioned that old builds would error-out as soon as he shut the old WCF service off. 

That sounds like what this is. v6 is running fine. :)
