### ISSUE TITLE
Disparity between release and dev builds

### ISSUE THREAD

**Issue by Javano** [TheRealDF/ADFGX_Cloud_Solver#14]
_Not so much an issue with the product as with the process:_ 

Would it be possible for you to try and commit builds as you tag and bag them for public consumption? 

Makes life hard for us forkers when the repo is often a build behind, knowing that pretty much any changes we make are just going to result in conflicts later down the line. :P

**Comment by EthanC** [comment]
Eventually, this project will be revived, and when that happens I'll make sure this isn't an issue :)
