### ISSUE TITLE
Virus in latest exe?

### ISSUE THREAD

**Issue by robocop99** [TheRealDF/ADFGX_Cloud_Solver#16]
Hey i'm not sure as to why it is doing this but when i try and download the latest file from:  http://fascinatinginformation.com/ADFGX_Cloud_Solver.exe my kaspersky keeps deleteing the exe as it thinks its a trojan. 

Was wondering if you guy were aware to this and whether we should be worried or not?

Attached image of kaspersky report 
![virus](https://cloud.githubusercontent.com/assets/6877911/19924241/006a0916-a0e3-11e6-8776-26408b679de5.jpg)

**Comment by EthanC** [comment]
The ADFGX Cloud Solver is 100% safe, and open source so you can see for yourself. That's merely a false positive, likely due to the poor AV Definitions from Kaspersky. Nothing to worry about.

**Comment by robocop99** [comment]
Well considering the .exe you can download from the website is a different version to the one on this repo is a bit concerning.

Please see here for information saying the repo is NOT up to date - https://github.com/TheRealDF/ADFGX_Cloud_Solver/issues/13
